concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths:
      - docs/**
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    # Build the site and upload artifacts using actions/upload-pages-artifact
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build docs
        uses: docker/bake-action@v3
        with:
          files: |
            docker-bake.hcl
          targets: docs-export
          set: |
            *.cache-from=type=gha,scope=docs
            *.cache-to=type=gha,scope=docs,mode=max
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./build/docs

  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 # or the latest "vX.X.X" version tag for this action
